#!/usr/bin/env bash
# Ce script modifie la résolution de localhost et facebook.com

sudo sed -i 's/127.0.0.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
